---
title: "incarceration.change.exploration"
author: "Sam Powers"
date: "1/9/2019"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)
load("incarceration.explore.Rdata")
library(tidyverse)
library(knitr)
library(RColorBrewer)
```

### 1) Look at various rates of crime as a proportion of the population 
# This is colorado-wide data 


```{r}
crime.rate.vis <- ggplot(crime.per, aes(x= year, y = crime.percent, color = class)) +
  geom_line() + 
  geom_point()+
  ggtitle('Crime Rate by Type Over Time') +
  theme(
    plot.title = element_text(size=15, face="bold", family = "serif", hjust = 0.5 ),
    axis.title.x = element_text(vjust=-0.5, size = 15, family ="serif"),
    axis.title.y = element_text(vjust=0.75,family ="serif", size = 15),
    axis.text.x=element_text(angle=50, size=10, vjust=0.5, family ="serif"),
    axis.text.y=element_text(angle= 0, size=10, vjust=.05,family ="serif"),
    panel.background = element_rect(fill = 'white'),
    panel.grid.major = element_line(colour = "grey", size = .3, linetype = "dashed" ),
    panel.grid.minor = element_line(colour = "white", size = .5),
    legend.text = element_text(family = "serif"), 
    legend.title = element_text(family = "serif", face = "bold"),
    legend.position = c(0.9, 0.50))+ 
  ylim(0, 4.0) +
  scale_x_continuous(breaks = seq(2008, 2017, 1), limits = c(2008,2017)) +
  labs(x="Year", y="Crime Rate (% of State Population)" , color = "Type of Crime")
crime.rate.vis
```

# This shows the Overall Incarceration Rate in Colorado over the Past few years


```{r}
incarc.rate.vis <- ggplot(incarceration.perc.co, aes(x= year, y = jail.perc)) +
  geom_line() + 
  geom_point()+
  ggtitle('CO Incarceration Rate Over Time') +
  theme(
    plot.title = element_text(size=15, face="bold", family = "serif", hjust = 0.5 ),
    axis.title.x = element_text(vjust=-0.5, size = 15, family ="serif"),
    axis.title.y = element_text(vjust=0.75,family ="serif", size = 15),
    axis.text.x=element_text(angle=50, size=10, vjust=0.5, family ="serif"),
    axis.text.y=element_text(angle= 0, size=10, vjust=.05,family ="serif"),
    panel.background = element_rect(fill = 'white'),
    panel.grid.major = element_line(colour = "grey", size = .3, linetype = "dashed" ),
    panel.grid.minor = element_line(colour = "white", size = .5)
  ) + 
  ylim(0, .5) +
  scale_x_continuous(breaks = seq(2008, 2017, 1), limits = c(2008,2017)) +
  labs(x="Year", y="Incarceration Rate (% of State Population)")
incarc.rate.vis
```


# Table of Incarceration Rates by County and Year
```{r}
county.incarc.table <- county.incarc.rate %>%
  select(year, county_name, incarc_perc) %>%
  spread(county_name, incarc_perc)
kable(county.incarc.table)
```

```{r}
incarc.diff.15.08.plot  <- ggplot(incarc.diff.15.08,
                         aes(x=reorder(county_name, -diff2015.08), y=diff2015.08, fill=changesign)) + 
                        stat_summary(fun.y="sum", geom="bar", position="dodge") + coord_flip() +
                         labs(x="County", y="2015 Incarceration Perc - 2008 Incarceration Perc",
                            title="Change in Incarceration Percentage of County Population (2015 - 2008)"
                                                 ) +   
  theme(
                                                   plot.title = element_text(size=15, face="bold", family = "serif", hjust = 0.5 ),
                                                   axis.title.x = element_text(vjust=-0.5, size = 15, family ="serif"),
                                                   axis.title.y = element_text(vjust=0.75,family ="serif", size = 15),
                                                   axis.text.x=element_text(angle=0, size=10, vjust=0.5, family ="serif"),
                                                   axis.text.y=element_text(angle= 0, size=10, vjust=.05,family ="serif"),
                                                   panel.background = element_rect(fill = 'white'),
                                                   panel.grid.major = element_line(colour = "grey", size = .3, linetype = "dashed" ),
                                                   panel.grid.minor = element_line(colour = "white", size = .5)
                                                 ) + 
  guides(fill=FALSE)

incarc.diff.15.08.plot
```

```{r}
Rel.Change.plot  <- ggplot(filter(perc.change.data, abs(dif_in_dif) < 150 ) ,
                           aes(x= dif_15to64_pop, y=dif_jail_pop)) + 
  geom_point()+
  ggtitle('% Change in Incarceration v % Change in Population (2015 - 2008)') +
  theme(
    plot.title = element_text(size=15, face="bold", family = "serif", hjust = 0.5 ),
    axis.title.x = element_text(vjust=-0.5, size = 15, family ="serif"),
    axis.title.y = element_text(vjust=0.75,family ="serif", size = 15),
    axis.text.x=element_text(angle=0, size=10, vjust=0.5, family ="serif"),
    axis.text.y=element_text(angle= 0, size=10, vjust=.05,family ="serif"),
    panel.background = element_rect(fill = 'white'),
    panel.grid.major = element_line(colour = "grey", size = .5, linetype = "dashed" ),
    panel.grid.minor = element_line(colour = "grey", size = .3, linetype = "dashed")
  ) + 
  ylim(-75, 75) +
  scale_x_continuous(breaks = seq(-20, 20, 5), limits = c(-20,20)) +
  labs(x="% Change in Population", y="% Change in Jail Population") +
  geom_text(aes(label=county_name), hjust=-.1, vjust=.1, size = 2) +
  geom_hline(aes(yintercept = 0)) +
  geom_vline(aes(xintercept = 0)) +
  geom_abline(intercept = 0, slope = 1)


Rel.Change.plot
```





